#ifndef SuperpoweredLatency_machines
#define SuperpoweredLatency_machines

const char *machines[][2] = {
    { "iPhone1,1", "iPhone (first)" },
    { "iPhone1,2", "iPhone 3G" },
    { "iPhone2,1", "iPhone 3GS" },
    { "iPhone3,1", "iPhone 4" },
    { "iPhone3,3", "iPhone 4" },
    { "iPhone4,1", "iPhone 4S" },
    { "iPhone5,1", "iPhone 5" },
    { "iPhone5,2", "iPhone 5" },
    { "iPhone5,3", "iPhone 5c" },
    { "iPhone5,4", "iPhone 5c" },
    { "iPhone6,1", "iPhone 5s" },
    { "iPhone6,2", "iPhone 5s" },
    { "iPhone7,1", "iPhone 6 Plus" },
    { "iPhone7,2", "iPhone 6" },
    { "iPad1,1", "iPad (first)" },
    { "iPad2,1", "iPad 2" },
    { "iPad2,2", "iPad 2" },
    { "iPad2,3", "iPad 2" },
    { "iPad2,4", "iPad 2" },
    { "iPad2,5", "iPad mini (first)" },
    { "iPad2,6", "iPad mini (first)" },
    { "iPad2,7", "iPad mini (first)" },
    { "iPad3,1", "iPad 3" },
    { "iPad3,2", "iPad 3" },
    { "iPad3,3", "iPad 3" },
    { "iPad3,4", "iPad 4" },
    { "iPad3,5", "iPad 4" },
    { "iPad3,6", "iPad 4" },
    { "iPad4,1", "iPad Air (first)" },
    { "iPad4,2", "iPad Air (first)" },
    { "iPad4,3", "iPad Air (first)" },
    { "iPad4,4", "iPad mini 2" },
    { "iPad4,5", "iPad mini 2" },
    { "iPad4,6", "iPad mini 2" },
    { "iPad4,7", "iPad mini 3" },
    { "iPad4,8", "iPad mini 3" },
    { "iPad4,9", "iPad mini 3" },
    { "iPad5,3", "iPad Air 2" },
    { "iPad5,4", "iPad Air 2" },
    { "iPod1,1", "iPod touch (first)" },
    { "iPod2,1", "iPod touch (2nd gen)" },
    { "iPod3,1", "iPod touch (3rd gen)" },
    { "iPod4,1", "iPod touch (4th gen)" },
    { "iPod5,1", "iPod touch (5th gen)" },
    { NULL, NULL }
};

#endif
